// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGQuX6F-_MwyF3svLIn9GqI05C4We3-Uo',
    appId: '1:586037416930:web:c5ee32475faddfaafb9fbb',
    messagingSenderId: '586037416930',
    projectId: 'pim-expenses-splitter',
    authDomain: 'pim-expenses-splitter.firebaseapp.com',
    storageBucket: 'pim-expenses-splitter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl8Qcjz-C8CsJ7tX7w3emZ7e9nOmAfxy0',
    appId: '1:586037416930:android:9b692cd8c93b8083fb9fbb',
    messagingSenderId: '586037416930',
    projectId: 'pim-expenses-splitter',
    storageBucket: 'pim-expenses-splitter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz6AYAwPJ9sUKqR_JnzBGATAJZfpJYI2M',
    appId: '1:586037416930:ios:2fbb5061c03c3795fb9fbb',
    messagingSenderId: '586037416930',
    projectId: 'pim-expenses-splitter',
    storageBucket: 'pim-expenses-splitter.firebasestorage.app',
    iosBundleId: 'com.example.expencesSpliter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz6AYAwPJ9sUKqR_JnzBGATAJZfpJYI2M',
    appId: '1:586037416930:ios:2fbb5061c03c3795fb9fbb',
    messagingSenderId: '586037416930',
    projectId: 'pim-expenses-splitter',
    storageBucket: 'pim-expenses-splitter.firebasestorage.app',
    iosBundleId: 'com.example.expencesSpliter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGQuX6F-_MwyF3svLIn9GqI05C4We3-Uo',
    appId: '1:586037416930:web:24d14d193b149b4ffb9fbb',
    messagingSenderId: '586037416930',
    projectId: 'pim-expenses-splitter',
    authDomain: 'pim-expenses-splitter.firebaseapp.com',
    storageBucket: 'pim-expenses-splitter.firebasestorage.app',
  );
}
